server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8082/eureka/}
  instance:
    instance-id: backend-instance-${random.uuid}
spring:
  application:
    name: backend